export const defaults = {
    JWT_EXPIRE: '30m',
    SERVICE_JWT_EXPIRE: '300d',
    JWT_REFRESH_TOKEN_EXPIRE: '1d',
    JWT_EXPIRE_SECONDS: 60 * 30,
    SERVICE_JWT_EXPIRE_SECONDS: 60 * 60 * 24 * 300,
    JWT_REFRESH_TOKEN_EXPIRE_SECONDS: 60 * 60 * 24,
};
